services:
  ingest:
    profiles:
      - local
    depends_on:
      elasticsearch:
        condition: service_healthy
    build:
      context: .
      target: ingest
    volumes:
      - ./lib:/app/lib
      - ./scripts:/app/scripts
      - ./conf:/app/conf
    networks:
      - elasticsearch

  ingest-test:
    profiles:
      - test
    depends_on:
      elasticsearch-test:
        condition: service_healthy
    build:
      context: .
      target: ingest-dev
    environment:
      INGEST_TEST: 1
    volumes:
      - ./lib:/app/lib
      - ./bin:/app/bin
      - ./scripts:/app/scripts
      - ./t:/app/t
      - ./conf:/app/conf
      - ./test_data:/app/test_data
    networks:
      - elasticsearch

  elasticsearch:
    profiles:
      - local
    image: elasticsearch:8.19.9
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    healthcheck:
      timeout: 5s
      start_period: 60s
      test: ["CMD", "curl", "--fail", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"]
    ports:
      - "9200"
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    networks:
      - elasticsearch

  elasticsearch-test:
    profiles:
      - test
    image: elasticsearch:8.19.9
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    healthcheck:
      timeout: 5s
      start_period: 60s
      test: ["CMD", "curl", "--fail", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"]
    ports:
      - "9200"
    volumes:
      - type: volume
        source: elasticsearch-test
        target: /usr/share/elasticsearch/data
    networks:
      - elasticsearch

networks:
  elasticsearch:

volumes:
  elasticsearch:
  elasticsearch-test:
