---
# Use the latest 2.1 version of CircleCI pipeline process engine. See:
# https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  codecov: codecov/codecov@4.1.0
# Orchestrate or schedule a set of jobs
workflows:
  docker-compose:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    machine: true
    resource_class: large
    steps:
      - run:
          name: docker-compose version
          command: docker-compose --version
      - run:
          command: |
            git clone https://github.com/metacpan/metacpan-docker.git
            cd metacpan-docker
          name: metacpan-docker checkout
      - checkout:
          path: metacpan-docker/src/metacpan-ingest
      - run:
          command: |
            pushd metacpan-docker
            ./bin/metacpan-docker init
          name: clone missing repositories
      - run:
          command: |
            pushd metacpan-docker
            docker-compose build --build-arg CPM_ARGS='--with-test' insgest_test
          name: compose build
      - run:
          command: |
            pushd metacpan-docker
            ./bin/metacpan-docker init
            docker-compose --verbose up -d ingest_test
          name: compose up
      - run:
          command: |
            pushd metacpan-docker
            docker-compose exec -T ingest_test cpm install -g Devel::Cover
          name: install Devel::Cover
      # Since we're running docker-compose -d, we don't actually know if
      # Elasticsearch is available at the time this build step begins. We
      # probably need to wait for it here, so we'll add our own check.
      - run:
          command: |
            pushd metacpan-docker
            ./src/metacpan-ingest/wait-for-es.sh http://localhost:9200 elasticsearch_test
          name: wait for ES
      - run:
          command: |
            pushd metacpan-docker
            docker build . -t metacpan/metacpan-ingest && docker compose run ingest env PLACK_ENV=dev HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^t/|^test-data/|^etc/" prove -lrv --jobs 4 t
#            docker-compose exec -T ingest_test env PLACK_ENV=dev HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^t/|^test-data/|^etc/" prove -lr --jobs 4 t
          name: run tests with coverage
      # We are relying on environment variables from the host to be available when
      # we publish the report, so we publish from the host rather than trying
      # to propagate env variables to the container.
      - run:
          command: |
            pushd metacpan-docker
            docker-compose exec -T ingest_test cover -report json
          name: create coverage report
      - codecov/upload:
          file: metacpan-docker/src/metacpan-ingest/cover_db/cover.json
      - run:
          command: |
            pushd metacpan-docker
            docker-compose logs
            docker stats --no-stream
            docker ps -a | head
          name: docker-compose logs
          when: on_fail
